# bad practice! TODO: just put secrets into cluster and do not store them anywhere else
apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  POSTGRES_PASSWORD: YWN0aXg=
stringData:
  POSTGRES_USER: actix